logLevel: info
hub:
  slack:
    webhooks: {}

replicaCount: 1

image:
  repository: docker.io/andreclaudino/pombo-correio
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: pombo.local.svc
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 1500m
    memory: 20Mi
  requests:
    cpu: 300m
    memory: 20Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90

nodeSelector: {}

tolerations: []

affinity: {}
