apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
data:
  {{- with .Values.hub }}
  hub.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
